version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      SECRET_KEY: "django-insecure-equalifica-dev"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    volumes:
      - ./:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"