# Generated by Django 5.2.7 on 2025-10-22 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('acessibilidade', models.JSONField(default=dict, help_text="Ex: {'libras': true, 'legendas': true, 'descricao_alt': true}")),
                ('cnpj_empresa', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cpf_pcd', models.CharField(max_length=14)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entrevista', 'Entrevista Agendada'), ('rejeitado', 'Rejeitado'), ('contratado', 'Contratado')], default='pendente', max_length=20)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='recruitment.vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'unique_together': {('vaga', 'cpf_pcd')},
            },
        ),
    ]
