# Generated by Django 5.2.7 on 2025-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_entrevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='acessibilidade_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vaga',
            name='experiencia_minima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaga',
            name='hard_skills_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vaga',
            name='soft_skills_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='acessibilidade',
            field=models.JSONField(blank=True, help_text="Ex: {'libras': true, 'legendas': true, 'descricao_alt': true}"),
        ),
    ]
