# Generated by Django 5.2.7 on 2025-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_vaga_acessibilidade_vetor_vaga_experiencia_minima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Resumo dos principais requisitos'),
        ),
    ]
