# Generated by Django 4.2.7 on 2025-11-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('recruitment', '0004_alter_vaga_requisitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Cidade/Estado ou Remoto', max_length=200),
        ),
        migrations.AddField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=20),
        ),
    ]
