# Generated by Django 4.2.7 on 2025-11-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_vaga_empresa_vaga_localizacao_vaga_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entrevista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vaga',
            options={},
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cnpj_empresa',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cpf_pcd',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.vaga'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='candidatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.candidatura'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='link_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='acessibilidade',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='acessibilidade_vetor',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='cnpj_empresa',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='hard_skills_vetor',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='localizacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='requisitos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='soft_skills_vetor',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada')], default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
