# Generated by Django 4.2.7 on 2025-11-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_candidatura_options_alter_entrevista_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatura',
            options={'verbose_name': 'Candidatura', 'verbose_name_plural': 'Candidaturas'},
        ),
        migrations.AlterModelOptions(
            name='entrevista',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vaga',
            options={'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='status',
        ),
        migrations.AddField(
            model_name='entrevista',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cnpj_empresa',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cpf_pcd',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('entrevista', 'Entrevista Agendada'), ('rejeitado', 'Rejeitado'), ('contratado', 'Contratado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='recruitment.vaga'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='candidatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista', to='recruitment.candidatura'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='link_video',
            field=models.URLField(blank=True, help_text='Link para sala de vídeo (ex: Zoom, Google Meet)', null=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='acessibilidade',
            field=models.JSONField(blank=True, help_text="Ex: {'libras': true, 'legendas': true, 'descricao_alt': true}"),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='acessibilidade_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='cnpj_empresa',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='hard_skills_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Resumo dos principais requisitos'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='soft_skills_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
