# Generated by Django 5.2.7 on 2025-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcdprofile',
            name='acessibilidade_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pcdprofile',
            name='experiencia_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pcdprofile',
            name='hard_skills_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pcdprofile',
            name='soft_skills_vetor',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pcdprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Liste suas habilidades e competências (Separadas por Vírgula).'),
        ),
    ]
