# Generated by Django 5.2.7 on 2025-10-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('libras_para_audio', 'Libras → Áudio'), ('audio_para_libras', 'Áudio → Libras')], max_length=20)),
                ('cpf_pcd', models.CharField(max_length=14)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('conteudo_original', models.TextField(blank=True, help_text='Texto ou URL do áudio/vídeo original')),
                ('conteudo_traduzido', models.TextField(blank=True, help_text='Texto traduzido ou URL do resultado')),
                ('duracao_segundos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Log de Acessibilidade',
                'verbose_name_plural': 'Logs de Acessibilidade',
            },
        ),
    ]
