# Generated by Django 5.2.7 on 2025-10-22 22:41

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Formato: XX.XXX.XXX/0001-XX ou XXXXXXXXX0001XX', max_length=18, unique=True, validators=[common.validators.validate_cnpj], verbose_name='CNPJ')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recrutadores', to='companies.empresa')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Recrutador',
                'verbose_name_plural': 'Recrutadores',
            },
        ),
    ]
